version: '3.8'

services:
  db:
    image: supabase/postgres:15.1.0.118
    container_name: supabase_db
    environment:
      POSTGRES_PASSWORD: your-super-secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  studio:
    image: supabase/studio:20240307-4e4c2c5
    container_name: supabase_studio
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: your-super-secret
    depends_on:
      - meta

  kong:
    image: kong:2.8.1
    container_name: supabase_kong
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
    volumes:
      - ./kong.yml:/var/lib/kong/kong.yml
    depends_on:
      - auth
      - rest
      - realtime

  auth:
    image: supabase/gotrue:v2.103.1
    container_name: supabase_auth
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:your-super-secret@db:5432/postgres?sslmode=disable
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: http://localhost:3000,http://localhost:3001
      GOTRUE_DISABLE_SIGNUP: 'false'
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
    depends_on:
      - db

  rest:
    image: postgrest/postgrest:v11.0.0
    container_name: supabase_rest
    environment:
      PGRST_DB_URI: postgres://postgres:your-super-secret@db:5432/postgres
      PGRST_DB_SCHEMA: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token
      PGRST_DB_USE_LEGACY_GUCS: 'false'
    depends_on:
      - db

  realtime:
    image: supabase/realtime:v2.10.3
    container_name: supabase_realtime
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: your-super-secret
      DB_NAME: postgres
      DB_AFTER_CONNECT_QUERY: 'CREATE SCHEMA IF NOT EXISTS realtime; GRANTE USAGE ON SCHEMA realtime TO postgres, anon, authenticated, service_role;'
      PORT: 4000
      JWT_SECRET: your-super-secret-jwt-token
      REPLICATION_MODE: RLS
    depends_on:
      - db

  meta:
    image: supabase/postgres-meta:v0.66.0
    container_name: supabase_meta
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: your-super-secret
    depends_on:
      - db

  storage:
    image: supabase/storage-api:v0.40.4
    container_name: supabase_storage
    environment:
      DATABASE_URL: postgres://postgres:your-super-secret@db:5432/postgres
      PGRST_JWT_SECRET: your-super-secret-jwt-token
      FILE_STORAGE_BACKEND: disk
      FILE_STORAGE_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: 'true'
    volumes:
      - storage_data:/var/lib/storage
    depends_on:
      - db

  imgproxy:
    image: darthsim/imgproxy:v3.7.0
    container_name: supabase_imgproxy
    environment:
      IMGPROXY_BIND: :5000
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: 'true'
    volumes:
      - storage_data:/storage:ro
    depends_on:
      - storage

volumes:
  db_data:
  storage_data:
